meta:
  api_name: "ABDA API"
  api_description: "A REST-like API to access the ABDA Database."
  api_version: "0.1.0"
  api_url: "medinfo.precisiondosing.de"
  group: "/api/v1"
server:
  read_write_timeout: "120s"
  idle_timeout: "30s"
  address: ":3333"
log:
  file_name: "/logs/abda_api.log"
  level: "INFO"
  max_size: 50
  max_backups: 3
database:
  db_name: "abda"
  max_open_conns: 50
  max_idle_conns: 10
  max_conn_lifetime: "1h"
auth_token:
  access_expiration_time: "15m"
  refresh_expiration_time: "24h"
  issuer: "https://medinfo.precisiondosing.de"
reset_token:
  expiration_time: "48h"
  retry_interval: "24h"
limits:
  interaction_drugs: 100
  batch_queries: 100
  batch_jobs: 25
