name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_LOGIN }}
          password: ${{ secrets.GH_PACKAGE_PAT }}

      - name: Build and push the image
        run: |
          docker build --no-cache . --tag ghcr.io/Clinical-Pharmacy-Saarland-University/abdataapi-go:latest
          docker push ghcr.io/Clinical-Pharmacy-Saarland-University/abdataapi-go:latest
